### ISSUE TITLE
whole data

### ISSUE THREAD

**Issue by BingCS** [jenspetersen/gqn-pytorch#2]
Dear jenspetersen,

I checked the gqn dataset from https://github.com/deepmind/gqn-datasets. Shepard_metzler_7_parts contains 900 tfrecords for training. Each tfrecord has 20 scenes. So there are only 18000 scenes. For Mazes, there are 1080 records with 100 scenes for each record, which means 108000 in total.

So I think this link just contains a part of the whole data, right? If so, could you send the link for the whole dataset? Many thanks ion advance!

Best,
Bing

**Comment by jenspetersen** [comment]
Shepard-Metzler-7 should have 810000 training instances/scenes and 200000 test instances at a sequence length of 15, mazes has 108000 training and 12000 test instances at q sequence length of 300. I don't know where you tried to download the data, but I can see the full SM7 training set here:

https://console.cloud.google.com/storage/browser/gqn-dataset/shepard_metzler_7_parts/train/
